// <auto-generated />
namespace E02_EF6_CF_Migrations_Books_DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class M02_BookUpField_DDC : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(M02_BookUpField_DDC));
        
        string IMigrationMetadata.Id
        {
            get { return "202207182200529_M02_Book-UpField_DDC"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
