// <auto-generated />
namespace RSGym_DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class M02_Up_CompletedAt : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(M02_Up_CompletedAt));
        
        string IMigrationMetadata.Id
        {
            get { return "202207312349345_M02_Up_CompletedAt"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
